### ISSUE TITLE
Error in Spreedly.Base process_response never matches. (Critical)

### ISSUE THREAD

**Issue by mitcheaton1** [spreedly/spreedly-elixir#25]
So it looks like the spreedly elixir library might be broken. It was working for us until today. 

<img width="893" alt="Screen Shot 2020-01-24 at 3 43 42 PM" src="https://user-images.githubusercontent.com/218058/73111738-52ae0280-3ec0-11ea-9854-96a0204147e9.png">

it looks like the httpoison response in Spreedly.Base never matches parse_response. i threw a debugger and the api_request method in the Base module returns only an HTTPoison Struct. It doesn't return an ok or error tuple which parse_response expects. 

i put in a catch all at the bottom

`defp process_response(error) do
   IO.inspect(error)
  end`

which just returns a %HTTPoison.Response{}  instead of {_status, %HTTPoison.Response{}}

Using HTTPoison 1.6.2 in according to mix.lock

**Comment by jknipp** [comment]
@mitcheaton1 Would you mind adding more details such as Elixir version, Erlang version, and the function  API function you are using?

**Comment by jknipp** [comment]
@mitcheaton1  Running tests against the `HTTPoison`  1.3.1 used by the `mix.lock` file does not produce this issue. However, when I upgraded to HTTPoison 1.6.2, I was able to reproduce the issue you are seeing.

It appears that the changes introduce with HTTPoison 1.4.0, specifically this [commit](https://github.com/edgurgel/httpoison/commit/cd5f6b6be05803fa29d4c5a2678c250b7adcc79e)  to add a public function named `process_response/1` in `HTTPoison.Base`, conflict with the private `process_response/1` function we have in `Spreedly.Base`. 

My recommendation is to downgrade HTTPoison if you need this right away, until we have time to patch it.

**Comment by mitcheaton1** [comment]
Sorry yeah I’m using httpoison 1.6.2. Latest elixir

**Comment by jknipp** [comment]
@mitcheaton1 I've published a fix for this in version `2.2.0`. This should now work with recent versions of HTTPoison.

**Comment by mitcheaton1** [comment]
Thanks!
